### ISSUE TITLE
Crash with abuse rate limits

### ISSUE THREAD

**Issue by elouanKeryell-Even** [piceaTech/node-gitlab-2-github#28]
After having migrated ~20 milestones & ~10 issues, the program crashed on an issue creation request, with the following error message:

```
Error: {"message":"You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.","documentation_url":"https://developer.github.com/v3/#abuse-rate-limits"}
```

Reading [this section](https://developer.github.com/v3/#abuse-rate-limits) & [this section](https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits) from the official docs, I guess the problem comes from performing more than 1 request per second.

I'd say this program doesn't take precautions in term of github rate abuse limits, but I'm really puzzled by the fact that the README mentions a successful 300 issues migration

**Comment by spruce** [comment]
Hey,
you are right. There are no measures in place to combat that. I did migrate some time ago, it's possible that github has changed some detections in the mean time. If you'd like to create a solution for it. I would be happy. Currently not my main focus. But if I have time I'd like to rewrite major parts of this project.

**Comment by spruce** [comment]
If I rewrite more I want to build this into this project but I hope it will be handled by https://github.com/octokit/rest.js/issues/526

**Comment by yunti** [comment]
Looks like rate limiting was implemented in the last week https://github.com/octokit/rest.js/issues/1099

**Comment by mattip** [comment]
Any more thoughts here? If it is not the `@` mention, what else could it be?

**Comment by mattip** [comment]
Maybe there are different limits for private and public free repos. I am trying to import pypy/pypy which has over 3500 issues, many with @user notifications. In order to avoid spamming the owner team, I am trying to import the repo via a private repo under my github user, that way it will not send out notifications.

**Comment by mattip** [comment]
Digging around a bit, I found [another issue converter](https://github.com/knoepfel/redmine-migration/blob/148f07efe66122a89130b5b595c1bdd19ba079f5/migrate-issues.py#L65) that waits 15 minutes when hitting a secondary rate limit. I think that limit is hit every 30 issues, so converting 3500 issues will take me ~30 hours?

**Comment by mattip** [comment]
Now my conversion rate is down to 25 issues / hour otherwise I get an error

**Comment by mattip** [comment]
PR #109 uses throttling, and that works as advertised. I tried it out.

One consequence of this approach is that it takes ~10 minutes to upload 25 issues, then the throttling kicks in (for me, maybe because I am using a private repo as a free user?). It then takes the rest of an hour to clear the abuse flag. During that time, I cannot interact with github since my username is flagged for abuse. So this PR is doing what it promises.

On the other hand, rather than depend on the throttling, I increased the timeout before creating issues to 144 seconds which limits me to under 25 issues an hour. This seems to avoid the throttling and allows me to continue interacting with github while the issue migration slowly churns away.

**Comment by mattip** [comment]
Apparently there is a different endpoint for issue creation at https://api.github.com/repos/${GITHUB_USERNAME}/${GIHUB_REPONAME}/import/issues, see [this gist](https://gist.github.com/jonmagic/5282384165e0f86ef105). Since it does not send notifications, it is not subject to the secondary rate limit.

**Comment by akaihola** [comment]
>different endpoint for issue creation

Have you seen a similar one for pull request creation @mattip?

**Comment by mattip** [comment]
no idea sorry. Maybe someone who understands this more than me could try the  `https://api.github.com/repos/${GITHUB_USERNAME}/${GIHUB_REPONAME}/import/prs` endpoint?

**Comment by akaihola** [comment]
> import/prs

@mattip where did you find information about that endpoint?

**Comment by mattip** [comment]
I asked github support. I will ask if there is any information about pull requests.

**Comment by mattip** [comment]
Github support replied:


> Is there more documentation around about the `https://api.github.com/repos/${GITHUB_USERNAME}/${GITHUB_REPONAME}/import/*` endpoints?

There is no official documentation on the use of that endpoint.

> Is the only one `issues` or is there also a `PRs` endpoint as well?

Just issues only, there is no similar one for PR.

**Comment by mattip** [comment]
It turns out there is an [octokit.request](https://github.com/octokit/octokit.js#octokitrequest) function, so theoretically that could be used to refactor `githubHelper.createIssueAndComments()`.

**Comment by mattip** [comment]
It seems the new API is optionally used in #116.
