### ISSUE TITLE
RequestError [HttpError]: Validation Failed: "No commits between master and dev_01"

### ISSUE THREAD

**Issue by makeitmin** [piceaTech/node-gitlab-2-github#91]
Thank you for this awesome project.
In my case, all features work well except for **Transferring Merge Request**.
I tried to solve this error but I couldn't get any clues from GitHub API docs..

It brings all of Merge Requests from my GitLab successfully, but I think problem is Creating Pull Requests to my GitHub.
I'd like to know if you have any idea for this.
Error occurs like :

```
Creating pull request: !4 - dev-01_MR_0226 // -> this is one of my MR titles
Could not create pull request: !4 - dev-01_MR_0226
RequestError [HttpError]: Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between master and dev_01"}
    at C:\node-gitlab-2-github\node_modules\@octokit\request\dist-src\fetch-wrapper.js:49:31      
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  status: 422,
  headers: {
    // I'll skip it ! It's too long.
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/makeitmin/skidmarker/pulls',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.0.0 octokit-core.js/3.1.0 <environment undetectable>',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"title":"dev-01_MR_0226","body":"In GitLab by @Seongmin on Feb 26, 2021, 18:32\\n\\n## Issues\\n axios post url error","head":"dev_01","base":"master"}',
    request: { hook: [Function: bound bound register] }
  },
  errors: [
    {
      resource: 'PullRequest',
      code: 'custom',
      message: 'No commits between master and dev_01'
    }
  ],
  documentation_url: 'https://docs.github.com/rest/reference/pulls#create-a-pull-request'
}
```

**Comment by mizuki0414** [comment]
@makeitmin Hi, I also encountered the same error, so I investigated it. Are you trying to make the request that has already been merged? I think already merged requests should result in an error because there are no differences between branches in Github. This tool seems to create a merged request as an issue on Github, but it takes a long time.

Therefore, we have taken the following two measures.

1.Starting with creating a new merge request (because it's likely to be open)

```diff 
index.ts
-- mergeRequests = mergeRequests.sort((a, b) => a.iid - b.iid);
++ mergeRequests = mergeRequests.sort((a, b) => b.iid - a.iid);
``` 

2. Only open merge requests are created because merged and closed ones are taking a long time.
※The following includes the modification of 1.

```diff 
index.ts
-- mergeRequests = mergeRequests.sort((a, b) => a.iid - b.iid);
++ mergeRequests = mergeRequests.filter(x => x.state === 'open').sort((a, b) => b.iid - a.iid);
``` 

I am taking the above measures.

Please let me know if there is another good solution.

Thank you.

**Comment by john-forrest** [comment]
I too have hit this issue and I agree with the basic analysis that it is because this tool is trying to create PRs where the branch has already been merged into the trunk. Not sure I quite like the solution though - we are switching from gitlab to github at work, and I would like to preserve as much history as possible from the original, even if I end up with MRs that are mapped to Issues.

To my mind, the preferable solution would be to trap the 422 error and if found to then fallback to creating an issue itself. However I have no node programming background so I will see what I can do. I am guessing it might be more feasible to fix  so that if the state is merged we always create an issue.

**Comment by spruce** [comment]
@makeitmin @mizuki0414 can one of you confirm that with the merge request it works?

**Comment by makeitmin** [comment]
Tested it and works well! Thank you :)
