### ISSUE TITLE
how to move files above 100MB

### ISSUE THREAD

**Issue by lsmith77** [piceaTech/node-gitlab-2-github#96]
Following https://github.com/piceaTech/node-gitlab-2-github#preliminaries

on the step `git push --no-verify --mirror git@github.com:username/repo.git` I am getting

```
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: ...
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File... is 166.01 MB; this exceeds GitHub's file size limit of 100.00 MB
```

Any hint on how to proceed?

**Comment by spruce** [comment]
Sorry for the delay. I hope you found the way to handle that?
Follow the link present the error message (http://git.io/iEPt8g).

git normally works with diffs of the files managed in the repos. If you add binary files no compression of the diffs can be made, making a repo bigger and worse to handle than necessary, therefore an alternative way of handling big files is used: git-lfs (large file storage).

Because this has nothing to do with this project I gonna close this issue. If you have more issues with this project feel free to open another issue 👍
